DATE_FORMAT = "%Y-%m-%d"

ENC_TYPE = 'utf-8'

PATH_TYPE_FOLDER = "FOLDER"
PATH_TYPE_FILE = "FILE"


PATH_LOCATION_SOURCE = "SOURCE"
PATH_LOCATION_TARGET = "TARGET"

RESULT_SUCCESS = "SUCCESS"
RESULT_FAIL = "FAIL"

FOLDER_ACTION_RENAME_CURRENT="R"
FOLDER_ACTION_ADD_SUB_FOLDER="A"
FOLDER_ACTION_DELETE_CURRENT="D"
FOLDER_ACTION_UPLOAD_FILE="U"

MPD_ITEM_STATE="state"

MPD_COMMAND_PLAY="play"
MPD_COMMAND_STOP="stop"
MPD_COMMAND_PAUSE="pause"
MPD_COMMAND_RESUME="resume"
MPD_COMMAND_STATUS="status"

EMOJI_PLAY=":arrow_forward:"
EMOJI_STOP=":black_square_for_stop:"
EMOJI_PAUSE=":double_vertical_bar:"
EMOJI_RESUME=":black_right_pointing_triangle_with_double_vertical_bar:"
EMOJI_REPEAT=":repeat:"
EMOJI_REPEAT_ONE=":repeat_one:"

