S_SERVER_LIST = "S_SERVER_LIST"
S_CURRENT_SERVER_NAME = "S_CURRENT_SERVER_NAME"

S_CURRENT_TARGET_FOLDER = "S_CURRENT_TARGET_FOLDER"

S_CURRENT_TARGET_FOLDER_DISPLAY = "S_CURRENT_TARGET_FOLDER_DISPLAY"


S_UI_VOLUME="S_UI_VOLUME"

S_UI_LOOP_REPEAT="S_UI_LOOP_REPEAT"
S_UI_LOOP_SINGLE="S_UI_LOOP_SINGLE"
S_UI_LOOP_RANDOM="S_UI_LOOP_RANDOM"
S_UI_LOOP_CONSUME="S_UI_LOOP_CONSUME"

S_UI_QUEE_CLEAR="S_UI_QUEE_CLEAR"

