S_SERVER_LIST = "S_SERVER_LIST"
S_CURRENT_SERVER_NAME = "S_CURRENT_SERVER_NAME"

S_CURRENT_TARGET_FOLDER = "S_CURRENT_TARGET_FOLDER"

S_CURRENT_TARGET_FOLDER_DISPLAY = "S_CURRENT_TARGET_FOLDER_DISPLAY"

S_CURRENT_SELECT_ITEM_QUEE = "S_CURRENT_SELECT_ITEM_QUEE"


S_UI_VOLUME="S_UI_VOLUME"

S_UI_LOOP_REPEAT="S_UI_LOOP_REPEAT"
S_UI_LOOP_SINGLE="S_UI_LOOP_SINGLE"
S_UI_LOOP_RANDOM="S_UI_LOOP_RANDOM"
S_UI_LOOP_CONSUME="S_UI_LOOP_CONSUME"

S_UI_QUEE_CLEAR="S_UI_QUEE_CLEAR"

S_UI_SELECT_COMMAND_PLAY="S_UI_SELECT_COMMAND_PLAY"
S_UI_SELECT_COMMAND_LOOP="S_UI_SELECT_COMMAND_LOOP"
S_UI_SELECT_COMMAND_QUEE="S_UI_SELECT_COMMAND_QUEE"
S_UI_SELECT_COMMAND_TARGET="S_UI_SELECT_COMMAND_TARGET"

# UI only
S_UI_QUEE_ITEM_COMMAND_CLEAR="clear"
S_UI_QUEE_ITEM_COMMAND_REMOVE="remove"
S_UI_QUEE_ITEM_COMMAND_UP="up"
S_UI_QUEE_ITEM_COMMAND_DOWN="down"


