S_SERVER_LIST = "S_SERVER_LIST"

# Current
S_CURRENT_SERVER_NAME = "S_CURRENT_SERVER_NAME"
S_CURRENT_TARGET_FOLDER = "S_CURRENT_TARGET_FOLDER"
S_CURRENT_TARGET_FOLDER_DISPLAY = "S_CURRENT_TARGET_FOLDER_DISPLAY"
S_CURRENT_SELECT_ITEM_QUEE = "S_CURRENT_SELECT_ITEM_QUEE"
S_CURRENT_SELECT_ITEM_TARGET = "S_CURRENT_SELECT_ITEM_TARGET"

# Volume
S_UI_VOLUME="S_UI_VOLUME"

# select default
S_UI_COMMON_ITEM_SELECT_INIT="select"


# Loop
S_UI_LOOP_REPEAT="S_UI_LOOP_REPEAT"
S_UI_LOOP_SINGLE="S_UI_LOOP_SINGLE"
S_UI_LOOP_RANDOM="S_UI_LOOP_RANDOM"
S_UI_LOOP_CONSUME="S_UI_LOOP_CONSUME"

# Play
S_UI_SELECT_COMMAND_PLAY="S_UI_SELECT_COMMAND_PLAY"
S_UI_SELECT_COMMAND_LOOP="S_UI_SELECT_COMMAND_LOOP"
S_UI_SELECT_COMMAND_QUEE="S_UI_SELECT_COMMAND_QUEE"
S_UI_SELECT_COMMAND_TARGET="S_UI_SELECT_COMMAND_TARGET"

# Quee
S_UI_QUEE_CLEAR="S_UI_QUEE_CLEAR"

# Quee Item
S_UI_QUEE_ITEM_COMMAND_CLEAR="clear"
S_UI_QUEE_ITEM_COMMAND_REMOVE="remove"
S_UI_QUEE_ITEM_COMMAND_UP="up"
S_UI_QUEE_ITEM_COMMAND_DOWN="down"
S_UI_QUEE_ITEM_COMMAND_PLAY="play"


# Target Item
S_UI_TARGET_ITEM_COMMAND_ADD_QUEE="Add Quee"
S_UI_TARGET_ITEM_COMMAND_VIEW_TAG="View Tag"
S_UI_TARGET_ITEM_COMMAND_DOWNLOAD="Download File"
