DATE_FORMAT = "%Y-%m-%d"

ENC_TYPE = 'utf-8'

PATH_TYPE_FOLDER = "FOLDER"
PATH_TYPE_FILE = "FILE"
PATH_TYPE_PARENT_FOLDER = "PARENT-FOLDER"

PATH_LOCATION_SOURCE = "SOURCE"
PATH_LOCATION_TARGET = "TARGET"

RESULT_SUCCESS = "SUCCESS"
RESULT_FAIL = "FAIL"

# Docker Internal
FOLDER_CONFIG = {
    'SOURCE': '/app/source',
    'TARGET': '/app/target'
}

FOLDER_ACTION_RENAME_CURRENT="R"
FOLDER_ACTION_ADD_SUB_FOLDER="A"
FOLDER_ACTION_DELETE_CURRENT="D"
FOLDER_ACTION_UPLOAD_FILE="U"

MPD_COMMAND_STATUS="status"
MPD_COMMAND_PLAY="play"
MPD_COMMAND_STOP="stop"
MPD_COMMAND_PAUSE="pause"
MPD_COMMAND_RESUME="resume"
MPD_COMMAND_NEXT="next"
MPD_COMMAND_PREVIOUS="previous"
MPD_COMMAND_VOLUME="volume"

MPD_COMMAND_REPEAT="repeat"
MPD_COMMAND_SINGLE="single"
MPD_COMMAND_RANDOM="random"
MPD_COMMAND_CONSUME="consume"